cart/urls.py
from django.urls import path

from . views import (
    cart_add, 
    cart_detail, 
    cart_remove
)

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
]

ecommerce/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    #Django admin
    path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('admin-panel-rozgor/', admin.site.urls),

    #Local apps
    
    path('cart', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('', include('shop.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

shop/urls.py
from shop.models import Category
from django.contrib import admin
from django.urls import path

from .views import CategoryListView, product_detail, product_list, CategoryDetailView, SearchResultsListView, CategoryListHomeView

app_name = 'shop'

urlpatterns = [
    path('', CategoryListHomeView.as_view(), name='category_list'),
    path('category/list/', CategoryListView.as_view(), name='categories'),
    path('category/<str:slug>/', CategoryDetailView.as_view(), name='category_detail'),
    path('<int:id>/<str:slug>/', product_detail, name='product_detail'),
    path('search/', SearchResultsListView.as_view(), name='search_results'),
]

shop/models.py
import os
from django.db import models
from django.db.models import indexes
from django.urls import reverse
import datetime
from django.utils import timezone
# Create your models here.

def get_upload_path(instance, filename):
    #  задаем название файла названием slug`а продукта
    filename = instance.slug + '.' + filename.split('.')[1]  
    return os.path.join('images/', filename)


class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    cover = models.CharField(max_length=500, null=True)

    class Meta:
        indexes = [
            models.Index(fields=['slug'], name='slug_index'),
        ]
        ordering = ('name',)
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:category_detail', args=[self.slug])


class Measurement(models.Model):
    name = models.CharField(max_length=50, db_index=True) 

    def __str__(self) -> str:
        return self.name   
    
    class Meta:
        verbose_name = 'Единица измерения'
        verbose_name_plural = 'Единицы измерения'




class Product(models.Model):
    category = models.ForeignKey(
        Category, related_name='products', 
        on_delete=models.CASCADE
        )
    measurement = models.ForeignKey(Measurement, related_name='measurement', null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    stock = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.CharField(max_length=500, null=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        indexes = [
            models.Index(fields=['id'], name='id_index'),
        ]
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])
    
    def was_added_recently(self):
        return self.created_at >= (timezone.now() - datetime.timedelta(days=7))
    
class Banner:
    name = models.CharField(max_length=50)
    photo = models.ImageField(upload_to=get_upload_path)

    class Meta:
        verbose_name = 'Баннер'
        verbose_name_plural = 'Баннеры'


    def __str__(self):
        return self.name

shop/views.py
from django.db.models import query
from django.db.models import Q
from django.shortcuts import render, get_object_or_404

from .models import Category, Product
from cart.forms import CartAddProductForm

from django.views.generic import (
    ListView,
    DetailView
)
'''
class ProductListView(ListView):
    template_name = 'shop/product/list.html'
    queryset = Product.objects.all()
    def get_context_data(self, **kwargs):
        context = super(ProductListView, self).get_context_data(**kwargs)
        context['category_list'] = Category.objects.all()
        return context
'''




def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=category)

    context = {
        'category': category,
        'categories': categories,
        'products': products
    }
    return render(request, 'shop/product/list.html', context)





def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    context = {
        'product': product,
        'cart_product_form': cart_product_form
    }
    return render(request, 'shop/product/detail.html', context)

class CategoryListHomeView(ListView):
    model = Category
    context_object_name = 'category_list'
    template_name = 'shop/product/list.html'

class CategoryListView(ListView):
    model = Category
    context_object_name = 'category_list'
    template_name = 'shop/product/category_list.html'

class CategoryDetailView(DetailView):
    model = Category
    context_object_name = 'category'
    template_name = 'shop/product/category_detail.html'

class SearchResultsListView(ListView):
    model = Product
    context_object_name = 'product_list'
    template_name = 'shop/product/search_results.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        return Product.objects.filter(
            Q(name__icontains=query) | Q(description__icontains=query)
        )

shop/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="интернет магазин, rozgor, uzrozgor, техника, продукты" />
    <meta name="description"
        content="Интеренет магазин: кодекс, rozgor, uzrozgor, интеренет магазин, продукты, заказы, доставка">
    <meta name="google-site-verification" content="A_M_z9Tv2AJAKrMr_Zj-FuuP0P7UT7ACcXRxJBjNpmM" />
    <meta name="yandex-verification" content="2d435396672672f7" />
    <link rel="shortcut icon" href="{% static 'img/basket.png' %}" />
    <title>{% block title %}ROZGOR{% endblock title %}</title>

    <!-- ===========ШРИФТЫ================= -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Balsamiq+Sans:ital,wght@1,700&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Work+Sans:wght@700&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Acme&display=swap" rel="stylesheet">
    <!-- =================Ссылки на файлы============= -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- ============================================== -->

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://unpkg.com/swiper@6.4.15/swiper-bundle.css" />
    <link rel="stylesheet" href="https://unpkg.com/swiper@6.4.15/swiper-bundle.min.css" />
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <script defer src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script defer src="https://unpkg.com/swiper@6.4.15/swiper-bundle.js"></script>
    <script defer src="https://unpkg.com/swiper@6.4.15/swiper-bundle.min.js"></script>
    <script defer src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script defer src="{% static 'js/script.js' %}"></script>

</head>

<body>
    <header class="header">
        <div class="container">
            <div class="header-overlay">
                <div class="nav-container">

                    <a href="{% url 'shop:category_list' %}" class="logo"><img src="{% static 'img/logo.png' %}"
                            alt=""></a>

                    <!-- НАВИГАЦИЯ -->
                    <div class="nav-wrapper">

                        <!-- Навигация для десктопа -->
                        <div class="poisk">
                            <form action="{% url 'shop:search_results' %}" method="GET">
                                <input name="q" class="write" placeholder="Qidirish" aria-label="Search">
                                <button class="send" type="submit"><img
                                        src="{% static 'img/searching-magnifying-glass.png' %}" alt=""></button>
                            </form>
                            <div class="header_left">
                                <div class="header_category">
                                    <a href="{% url 'shop:categories' %}">Toifalar</a>
                                </div>
                                <a href="{% url 'cart:cart_detail' %}">
                                    <div class="korzina" href="#">
                                        <div class="colich">{{cart.sum_of_items}}</div><img
                                            src="{% static './img/basket.png' %}" alt="">
                                    </div>
                                </a>
                            </div>

                        </div>

                        <!-- Кнопка для мобильной навигации -->
                        <div id="menu-togle" class="menu-icon">
                            <div class="menu-icon-line"></div>
                        </div>

                        <!-- Мобильная навигация -->
                        <div id="mobile-nav" class="mobile-nav">
                            <div class="mobile-nav__title">Navigatsiya</div>
                            <div class="mob_poisk">

                                <div class="mob_header_left">
                                    <a class="mob_korzina" href="{% url 'cart:cart_detail' %}">
                                        <div class="colich">{{cart.sum_of_items}}</div><img src="{% static './img/basket.png' %}" alt="">
                                    </a>

                                </div>
                                <div class="header_category">
                                    <a href="{% url 'shop:categories' %}">Toifalar</a>
                                </div>
                            </div>

                        </div>




                    </div>
                    <!-- // НАВИГАЦИЯ -->

                </div>
            </div>
        </div>
    </header>
    <section class="mob_poisk">
        <div class="container">
            <form action="{% url 'shop:search_results' %}" method="GET">
                <input class="mob_write" placeholder="Mahsulotlar bo'yicha qidirish" type="text">
                <button class="mob_send" type="submit"><img src="{% static 'img/searching-magnifying-glass.png' %}"
                        alt=""></button>
            </form>
        </div>
    </section>
    {% block content %}

    {% endblock content %}

    <section class="info">
        <div class="container-fluid">
            <div class="info-div col-md-3 col-sm-12"><img src="{% static 'img/headphone_nGU64yZ.png' %}" alt="">
                <h5>
                    7/24 xizmat ko'rsatish markazi</h5>
                <p>
                    Kechayu kunduz sizning xizmatingizda.</p>
            </div>
            <div class="info-div col-md-3 col-sm-12"><img src="{% static 'img/hand_ptGDetP.png' %}" alt="">
                <h5>
                    xavfsiz to'lov usuli</h5>
                <p>Qulay usulda to'lang.</p>
            </div>
            <div class="info-div col-md-3 col-sm-12"><img src="{% static 'img/box_YUWKLne.png' %}" alt="">
                <h5>Toshkent bo'ylab bepul etkazib berish.</h5>
                <p>
                    Buyurtmani siz uchun qulay vaqtda qabul qiling.</p>
            </div>
            <div class="info-div col-md-3 col-sm-12"><img src="{% static 'img/Shape_WtoAAPp.png' %}" alt="">
                <h5>
                    Ishonch bilan sotib oling</h5>
                <p>Mahsulotlarimiz sifat belgisiga ega.</p>
            </div>
        </div>
    </section>


    </main>


    <footer class="">
        <div class="container">
            <div class="bottom_top">
                <div class="wow fadeInLeft left_bottom col-lg-4" data-wow-delay="0.3s">
                    <a href="#" class="logo"><img src="{% static 'img/logo.png' %}" alt=""></a>

                    <p class="bot_p">Yangi mahsulotlarni siz uchun bizning do'konimizdan tez orada yetqazib beramiz.</p>
                </div>
                <div class="wow fadeInLeft center_bottom col-lg-4" data-wow-delay="0.6s">
                    <h4>Наш адрес</h4>
                    <div class="location">
                        <p class="bot_p">
                            Toshkent Piskent Bobur 38 uy
                        </p>
                    </div>
                    <div class="numb">

                        <p class="bot_p">+998 88 330 42 40 <br> +998 88 187 83 87</p>
                    </div>
                </div>
                <div class="wow fadeInLeft right_bottom col-lg-4" data-wow-delay="0.9s">
                    <h4>Информация</h4>

                    <ul class="bottom_nav">
                        <li><a href="https://t.me/uzrozgor">Telegram<img src="{% static 'img/telegram.png' %}"
                                    alt=""></a></li>
                        <li><a href="https://www.instagram.com/rozgor.official/?hl=ru">Instagram<img
                                    src="{% static 'img/instagram.png' %}" alt=""></a></li>
                        <li><a href="#">Facebook<img src="{% static 'img/facebook.png' %}" alt=""></a></li>
                        <li><a href="https://www.youtube.com/channel/UCVQLnJ4o_1PG2tCRwMoPBBA">YouTube<img
                                    src="{% static 'img/youtube.png' %}" alt=""></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
    <!-- ============================================== -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
        integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
        crossorigin="anonymous"></script>
</body>

</html>